package healthconnect;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author eskandar atrakchi
 * the GUI code is generated by NetBeans the logic is by eskandar atrakchi
 */
public class HealthConnectUI extends javax.swing.JFrame {

    JavaMethods jm = new JavaMethods();
    
    public HealthConnectUI() {
        initComponents();
        
        jm.getConnection();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }
    
    public void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        loginTAB = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        clearBTN = new javax.swing.JButton();
        ageLBL = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        fnameTF = new javax.swing.JTextField();
        updateBTN = new javax.swing.JButton();
        addressLBL = new javax.swing.JLabel();
        fnameLBL = new javax.swing.JLabel();
        lnameLBL = new javax.swing.JLabel();
        loginidLBL = new javax.swing.JLabel();
        deleteBTN = new javax.swing.JButton();
        lnameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        passwordLBL = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        displayBTN = new javax.swing.JButton();
        loginBTN1 = new javax.swing.JButton();
        signupBTN = new javax.swing.JButton();
        loginbackgroundLBL = new javax.swing.JLabel();
        appointmentTAB = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        chosendateLBL = new javax.swing.JLabel();
        chosendateTF = new javax.swing.JTextField();
        calendar = new com.toedter.calendar.JCalendar();
        doctornumberTF = new javax.swing.JTextField();
        doctornameTF = new javax.swing.JTextField();
        doctornameLBL = new javax.swing.JLabel();
        doctornumberLBL = new javax.swing.JLabel();
        confirmdateBTN = new javax.swing.JButton();
        appointmentdeleteBTN = new javax.swing.JButton();
        appointmentidTF = new javax.swing.JTextField();
        appointmentidLBL = new javax.swing.JLabel();
        appointmentbookBTN = new javax.swing.JButton();
        appointmentupdateBTN1 = new javax.swing.JButton();
        hideC = new javax.swing.JRadioButton();
        showC = new javax.swing.JRadioButton();
        appointmentidTF1 = new javax.swing.JTextField();
        appointmentidLBL1 = new javax.swing.JLabel();
        appointmentdisplayBTN = new javax.swing.JButton();
        appointmentbackgroundLBL = new javax.swing.JLabel();
        loginTAB2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        EHRdisplayBTN = new javax.swing.JButton();
        EHRcurrentmedicationTF = new javax.swing.JTextField();
        EHRalergyTF = new javax.swing.JTextField();
        EHRidTF = new javax.swing.JTextField();
        EHRmedicalhistoryTF = new javax.swing.JTextField();
        EHRcurrentmedicationLBL = new javax.swing.JLabel();
        EHRalergyLBL = new javax.swing.JLabel();
        EHRidLBL = new javax.swing.JLabel();
        EHRmedicalhistoryLBL = new javax.swing.JLabel();
        EHRupdateBTN = new javax.swing.JButton();
        EHRdeleteBTN = new javax.swing.JButton();
        EHRaddBTN = new javax.swing.JButton();
        EHRbackgroundLBL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        LightMode = new javax.swing.JMenu();
        cannotloginBTNTAB = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(null);

        clearBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(102, 102, 102));
        clearBTN.setText("Clear?");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        jPanel6.add(clearBTN);
        clearBTN.setBounds(140, 630, 100, 40);

        ageLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLBL.setForeground(new java.awt.Color(102, 102, 102));
        ageLBL.setText("Age");
        jPanel6.add(ageLBL);
        ageLBL.setBounds(420, 210, 80, 30);
        jPanel6.add(addressTF);
        addressTF.setBounds(30, 240, 260, 30);
        jPanel6.add(fnameTF);
        fnameTF.setBounds(420, 130, 280, 30);

        updateBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(102, 102, 102));
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        jPanel6.add(updateBTN);
        updateBTN.setBounds(610, 630, 100, 40);

        addressLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressLBL.setForeground(new java.awt.Color(102, 102, 102));
        addressLBL.setText("Address");
        jPanel6.add(addressLBL);
        addressLBL.setBounds(30, 210, 80, 30);

        fnameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnameLBL.setForeground(new java.awt.Color(102, 102, 102));
        fnameLBL.setText("First Name");
        jPanel6.add(fnameLBL);
        fnameLBL.setBounds(420, 100, 80, 30);

        lnameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnameLBL.setForeground(new java.awt.Color(102, 102, 102));
        lnameLBL.setText("Last Name");
        jPanel6.add(lnameLBL);
        lnameLBL.setBounds(30, 100, 80, 30);

        loginidLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginidLBL.setForeground(new java.awt.Color(102, 102, 102));
        loginidLBL.setText("Your ID");
        jPanel6.add(loginidLBL);
        loginidLBL.setBounds(420, 340, 80, 30);

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(102, 102, 102));
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        jPanel6.add(deleteBTN);
        deleteBTN.setBounds(490, 630, 100, 40);
        jPanel6.add(lnameTF);
        lnameTF.setBounds(30, 130, 260, 30);
        jPanel6.add(ageTF);
        ageTF.setBounds(420, 240, 280, 30);
        jPanel6.add(idTF);
        idTF.setBounds(420, 370, 280, 30);

        passwordLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLBL.setForeground(new java.awt.Color(102, 102, 102));
        passwordLBL.setText("Your Password");
        jPanel6.add(passwordLBL);
        passwordLBL.setBounds(30, 340, 110, 30);
        jPanel6.add(passwordTF);
        passwordTF.setBounds(30, 370, 250, 30);

        displayBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayBTN.setForeground(new java.awt.Color(102, 102, 102));
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        jPanel6.add(displayBTN);
        displayBTN.setBounds(250, 630, 100, 40);

        loginBTN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBTN1.setForeground(new java.awt.Color(102, 102, 102));
        loginBTN1.setText("Log-in");
        loginBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTN1ActionPerformed(evt);
            }
        });
        jPanel6.add(loginBTN1);
        loginBTN1.setBounds(370, 630, 100, 40);

        signupBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupBTN.setForeground(new java.awt.Color(102, 102, 102));
        signupBTN.setText("Sign-Up?");
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });
        jPanel6.add(signupBTN);
        signupBTN.setBounds(10, 630, 100, 40);

        loginbackgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackBackground.jpg"))); // NOI18N
        jPanel6.add(loginbackgroundLBL);
        loginbackgroundLBL.setBounds(0, 0, 730, 730);

        javax.swing.GroupLayout loginTABLayout = new javax.swing.GroupLayout(loginTAB);
        loginTAB.setLayout(loginTABLayout);
        loginTABLayout.setHorizontalGroup(
            loginTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        loginTABLayout.setVerticalGroup(
            loginTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("LOG-IN", loginTAB);

        jPanel8.setLayout(null);

        chosendateLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chosendateLBL.setForeground(new java.awt.Color(102, 102, 102));
        chosendateLBL.setText("The Chosen Date is");
        jPanel8.add(chosendateLBL);
        chosendateLBL.setBounds(260, 410, 150, 30);

        chosendateTF.setEditable(false);
        jPanel8.add(chosendateTF);
        chosendateTF.setBounds(430, 410, 270, 30);
        jPanel8.add(calendar);
        calendar.setBounds(0, 50, 710, 210);
        jPanel8.add(doctornumberTF);
        doctornumberTF.setBounds(430, 530, 270, 30);
        jPanel8.add(doctornameTF);
        doctornameTF.setBounds(430, 470, 270, 30);

        doctornameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctornameLBL.setForeground(new java.awt.Color(102, 102, 102));
        doctornameLBL.setText("Doctor Name");
        jPanel8.add(doctornameLBL);
        doctornameLBL.setBounds(290, 470, 120, 30);

        doctornumberLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctornumberLBL.setForeground(new java.awt.Color(102, 102, 102));
        doctornumberLBL.setText("Doctor Number");
        jPanel8.add(doctornumberLBL);
        doctornumberLBL.setBounds(290, 530, 120, 30);

        confirmdateBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmdateBTN.setForeground(new java.awt.Color(102, 102, 102));
        confirmdateBTN.setText("Confirm Date");
        confirmdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmdateBTNActionPerformed(evt);
            }
        });
        jPanel8.add(confirmdateBTN);
        confirmdateBTN.setBounds(10, 270, 130, 30);

        appointmentdeleteBTN.setText("Delete");
        jPanel8.add(appointmentdeleteBTN);
        appointmentdeleteBTN.setBounds(210, 630, 100, 40);
        jPanel8.add(appointmentidTF);
        appointmentidTF.setBounds(430, 360, 270, 30);

        appointmentidLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appointmentidLBL.setForeground(new java.awt.Color(102, 102, 102));
        appointmentidLBL.setText("Your ID");
        jPanel8.add(appointmentidLBL);
        appointmentidLBL.setBounds(340, 360, 70, 30);

        appointmentbookBTN.setText("Book");
        jPanel8.add(appointmentbookBTN);
        appointmentbookBTN.setBounds(580, 630, 100, 40);

        appointmentupdateBTN1.setText("Update");
        jPanel8.add(appointmentupdateBTN1);
        appointmentupdateBTN1.setBounds(450, 630, 100, 40);

        hideC.setBackground(new java.awt.Color(153, 153, 153));
        hideC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hideC.setForeground(new java.awt.Color(102, 102, 102));
        hideC.setText("Hide Calendar");
        hideC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideCActionPerformed(evt);
            }
        });
        jPanel8.add(hideC);
        hideC.setBounds(190, 20, 150, 21);

        showC.setBackground(new java.awt.Color(153, 153, 153));
        showC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showC.setForeground(new java.awt.Color(102, 102, 102));
        showC.setText("Show Calendar");
        showC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCActionPerformed(evt);
            }
        });
        jPanel8.add(showC);
        showC.setBounds(20, 20, 150, 20);
        jPanel8.add(appointmentidTF1);
        appointmentidTF1.setBounds(430, 310, 270, 30);

        appointmentidLBL1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appointmentidLBL1.setForeground(new java.awt.Color(102, 102, 102));
        appointmentidLBL1.setText("Appointment ID");
        jPanel8.add(appointmentidLBL1);
        appointmentidLBL1.setBounds(280, 310, 120, 30);

        appointmentdisplayBTN.setText("Display");
        jPanel8.add(appointmentdisplayBTN);
        appointmentdisplayBTN.setBounds(330, 630, 100, 40);

        appointmentbackgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackBackground.jpg"))); // NOI18N
        appointmentbackgroundLBL.setText("Di");
        jPanel8.add(appointmentbackgroundLBL);
        appointmentbackgroundLBL.setBounds(0, 0, 730, 730);

        javax.swing.GroupLayout appointmentTABLayout = new javax.swing.GroupLayout(appointmentTAB);
        appointmentTAB.setLayout(appointmentTABLayout);
        appointmentTABLayout.setHorizontalGroup(
            appointmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        appointmentTABLayout.setVerticalGroup(
            appointmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("APPOINTMENT ", appointmentTAB);

        jPanel9.setLayout(null);

        EHRdisplayBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRdisplayBTN.setForeground(new java.awt.Color(102, 102, 102));
        EHRdisplayBTN.setText("Print my EHR");
        jPanel9.add(EHRdisplayBTN);
        EHRdisplayBTN.setBounds(20, 630, 140, 40);
        jPanel9.add(EHRcurrentmedicationTF);
        EHRcurrentmedicationTF.setBounds(420, 340, 280, 30);
        jPanel9.add(EHRalergyTF);
        EHRalergyTF.setBounds(420, 230, 280, 30);
        jPanel9.add(EHRidTF);
        EHRidTF.setBounds(30, 230, 260, 30);
        jPanel9.add(EHRmedicalhistoryTF);
        EHRmedicalhistoryTF.setBounds(30, 340, 260, 30);

        EHRcurrentmedicationLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRcurrentmedicationLBL.setForeground(new java.awt.Color(102, 102, 102));
        EHRcurrentmedicationLBL.setText("Current Medication");
        jPanel9.add(EHRcurrentmedicationLBL);
        EHRcurrentmedicationLBL.setBounds(420, 310, 150, 30);

        EHRalergyLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRalergyLBL.setForeground(new java.awt.Color(102, 102, 102));
        EHRalergyLBL.setText("Alergy");
        jPanel9.add(EHRalergyLBL);
        EHRalergyLBL.setBounds(420, 200, 60, 30);

        EHRidLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRidLBL.setForeground(new java.awt.Color(102, 102, 102));
        EHRidLBL.setText("Your ID");
        jPanel9.add(EHRidLBL);
        EHRidLBL.setBounds(30, 200, 60, 30);

        EHRmedicalhistoryLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRmedicalhistoryLBL.setForeground(new java.awt.Color(102, 102, 102));
        EHRmedicalhistoryLBL.setText("Medical History");
        jPanel9.add(EHRmedicalhistoryLBL);
        EHRmedicalhistoryLBL.setBounds(30, 310, 140, 30);

        EHRupdateBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRupdateBTN.setForeground(new java.awt.Color(102, 102, 102));
        EHRupdateBTN.setText("Update");
        jPanel9.add(EHRupdateBTN);
        EHRupdateBTN.setBounds(580, 630, 100, 40);

        EHRdeleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRdeleteBTN.setForeground(new java.awt.Color(102, 102, 102));
        EHRdeleteBTN.setText("Delete");
        jPanel9.add(EHRdeleteBTN);
        EHRdeleteBTN.setBounds(460, 630, 100, 40);

        EHRaddBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EHRaddBTN.setForeground(new java.awt.Color(102, 102, 102));
        EHRaddBTN.setText("Add");
        jPanel9.add(EHRaddBTN);
        EHRaddBTN.setBounds(340, 630, 100, 40);

        EHRbackgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackBackground.jpg"))); // NOI18N
        jPanel9.add(EHRbackgroundLBL);
        EHRbackgroundLBL.setBounds(0, 0, 730, 730);

        javax.swing.GroupLayout loginTAB2Layout = new javax.swing.GroupLayout(loginTAB2);
        loginTAB2.setLayout(loginTAB2Layout);
        loginTAB2Layout.setHorizontalGroup(
            loginTAB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        loginTAB2Layout.setVerticalGroup(
            loginTAB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("EHR", loginTAB2);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("Date");
        jMenuBar1.add(date);

        time.setText("Time");
        jMenuBar1.add(time);

        LightMode.setText("Light-mode");
        LightMode.setToolTipText("Clcik me to switch the mode");
        LightMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LightModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(LightMode);

        cannotloginBTNTAB.setText("Can't Log-in?");
        cannotloginBTNTAB.setToolTipText("Clcik me to switch the mode");
        jMenuBar1.add(cannotloginBTNTAB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    private boolean isLightMode = true;
    
    private void LightModeMouseClicked(java.awt.event.MouseEvent evt) {                                       

        loginbackgroundLBL.setVisible(!isLightMode);
        appointmentbackgroundLBL.setVisible(!isLightMode);
        EHRbackgroundLBL.setVisible(!isLightMode);

        // note: will have to create  to be able to toggle other labels in other frames
        LightMode.setText(isLightMode ? "Dark-mode" : "Light-mode");
        isLightMode = !isLightMode;
    }                                      

    private void showCActionPerformed(java.awt.event.ActionEvent evt) {                                      

        calendar.setVisible(true);
    }                                     

    private void hideCActionPerformed(java.awt.event.ActionEvent evt) {                                      

        calendar.setVisible(false);
    }                                     

    private void confirmdateBTNActionPerformed(java.awt.event.ActionEvent evt) {                                               

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date selectedDate = calendar.getDate();

        String formattedDate = dateFormat.format(selectedDate);
        chosendateTF.setText(formattedDate);

    }                                              

    private void loginBTN1ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        int enteredPatientId = Integer.parseInt(idTF.getText());
        String enteredPassword = passwordTF.getText();

        jm.loginUser(enteredPatientId, enteredPassword);

    }                                         

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          

        try {
            String enteredId = idTF.getText();
            if (enteredId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a patientId before deleting.");
                return;
            }

            int patientId = Integer.parseInt(enteredId);
            jm.deleteUser(patientId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid patientId. Please enter a valid numeric value.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}


    }                                         

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        try {
            String newFirstName = HealthConnectUI.fnameTF.getText();
            int enteredPatientId = Integer.parseInt(idTF.getText());
            String newLastName = lnameTF.getText();
            String newAddress = addressTF.getText();
            int newAge = Integer.parseInt(ageTF.getText());

            // Retrieve the existing user profile
            UserProfile existingUserProfile = jm.getUserProfile(enteredPatientId);

            // Update the user information using setter methods
            existingUserProfile.setPatientFirstName(newFirstName);
            existingUserProfile.setPatientLastName(newLastName);
            existingUserProfile.setPatientAddress(newAddress);
            existingUserProfile.setPatientAge(newAge);

            // Call the updateUser method
            jm.updateUser(existingUserProfile);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving user profile: " + e.getMessage());
        }
    }                                         

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        jm.clearLoginTab();
        
    }                                        

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        int patientId = Integer.parseInt(idTF.getText());
        jm.displayUserData(patientId);
        
    }                                          

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        String patientFirstName = fnameTF.getText();
        int patientId = Integer.parseInt(idTF.getText());
        String patientLastName = lnameTF.getText();
        String patientAddress = addressTF.getText();
        int patientAge = Integer.parseInt(ageTF.getText());
        String patientPassword = passwordTF.getText();
        
        jm.registerUser(patientId, patientFirstName, patientLastName, patientAddress, patientAge, patientPassword);
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthConnectUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton EHRaddBTN;
    private javax.swing.JLabel EHRalergyLBL;
    public static javax.swing.JTextField EHRalergyTF;
    private javax.swing.JLabel EHRbackgroundLBL;
    private javax.swing.JLabel EHRcurrentmedicationLBL;
    public static javax.swing.JTextField EHRcurrentmedicationTF;
    private javax.swing.JButton EHRdeleteBTN;
    public static javax.swing.JButton EHRdisplayBTN;
    private javax.swing.JLabel EHRidLBL;
    public static javax.swing.JTextField EHRidTF;
    private javax.swing.JLabel EHRmedicalhistoryLBL;
    public static javax.swing.JTextField EHRmedicalhistoryTF;
    private javax.swing.JButton EHRupdateBTN;
    private javax.swing.JMenu LightMode;
    private javax.swing.JLabel addressLBL;
    public static javax.swing.JTextField addressTF;
    private javax.swing.JLabel ageLBL;
    public static javax.swing.JTextField ageTF;
    private javax.swing.JPanel appointmentTAB;
    private javax.swing.JLabel appointmentbackgroundLBL;
    private javax.swing.JButton appointmentbookBTN;
    private javax.swing.JButton appointmentdeleteBTN;
    private javax.swing.JButton appointmentdisplayBTN;
    private javax.swing.JLabel appointmentidLBL;
    private javax.swing.JLabel appointmentidLBL1;
    public static javax.swing.JTextField appointmentidTF;
    public static javax.swing.JTextField appointmentidTF1;
    private javax.swing.JButton appointmentupdateBTN1;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JMenu cannotloginBTNTAB;
    private javax.swing.JLabel chosendateLBL;
    public static javax.swing.JTextField chosendateTF;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton confirmdateBTN;
    private javax.swing.JMenu date;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JLabel doctornameLBL;
    public static javax.swing.JTextField doctornameTF;
    private javax.swing.JLabel doctornumberLBL;
    public static javax.swing.JTextField doctornumberTF;
    private javax.swing.JLabel fnameLBL;
    public static javax.swing.JTextField fnameTF;
    private javax.swing.JRadioButton hideC;
    public static javax.swing.JTextField idTF;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lnameLBL;
    public static javax.swing.JTextField lnameTF;
    private javax.swing.JButton loginBTN1;
    private javax.swing.JPanel loginTAB;
    private javax.swing.JPanel loginTAB2;
    private javax.swing.JLabel loginbackgroundLBL;
    private javax.swing.JLabel loginidLBL;
    private javax.swing.JLabel passwordLBL;
    public static javax.swing.JPasswordField passwordTF;
    private javax.swing.JRadioButton showC;
    private javax.swing.JButton signupBTN;
    private javax.swing.JMenu time;
    private javax.swing.JButton updateBTN;
    // End of variables declaration                   
}
